### ISSUE TITLE
panic: in net/netip.AddrFromSlice: cannot convert *t0 ([]byte) to [4]byte

### ISSUE THREAD

**Issue by congjunhua** [ondrajz/go-callvis#149]
```bash
$ go-callvis .
```
```bash
panic: in net/netip.AddrFromSlice: cannot convert *t0 ([]byte) to [4]byte

goroutine 5145 [running]:
golang.org/x/tools/go/ssa.emitConv(0xc018d47520, {0x100823af8, 0xc02df0d020}, {0x10081eae8?, 0xc008802720})
        golang.org/x/tools@v0.1.12/go/ssa/emit.go:251 +0x90e
golang.org/x/tools/go/ssa.(*builder).expr0(0xc02d7ffe18, 0xc018d47520, {0x10081fdc0?, 0xc007ed50c0?}, {0x7, {0x10081eae8, 0xc008802720}, {0x0, 0x0}})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:661 +0x765
golang.org/x/tools/go/ssa.(*builder).expr(0x1008200c0?, 0xc018d47520, {0x10081fdc0, 0xc007ed50c0})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:610 +0x187
golang.org/x/tools/go/ssa.(*builder).emitCallArgs(0xc018d47520?, 0xc018d47520, 0xc008c59600, 0xc007ed5100, {0x0?, 0x0, 0xc02d7ff128?})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:1030 +0x125
golang.org/x/tools/go/ssa.(*builder).setCall(0x1006b80a0?, 0xc008c6fb00?, 0xc007ed5100, 0xc02df12cc0)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:1092 +0x91
golang.org/x/tools/go/ssa.(*builder).expr0(0xc02d7ffe18, 0xc018d47520, {0x10081fdc0?, 0xc007ed5100?}, {0x7, {0x10081ebb0, 0xc009082000}, {0x0, 0x0}})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:686 +0x24e5
golang.org/x/tools/go/ssa.(*builder).expr(0x7?, 0xc018d47520, {0x10081fdc0, 0xc007ed5100})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:610 +0x187
golang.org/x/tools/go/ssa.(*builder).stmt(0xc018d47520?, 0xc018d47520, {0x100820300?, 0xc008c06a20?})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2161 +0x117b
golang.org/x/tools/go/ssa.(*builder).stmtList(...)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:911
golang.org/x/tools/go/ssa.(*builder).switchStmt(0xc02daec9c8?, 0xc018d47520, 0xc007ed3470, 0x0)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:1421 +0xd37
golang.org/x/tools/go/ssa.(*builder).stmt(0xc02d7ff978?, 0xc018d47520, {0x100820450?, 0xc007ed3470?})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2244 +0xe65
golang.org/x/tools/go/ssa.(*builder).stmtList(0xc02df0cf60?, 0x10?, {0xc008c06be0?, 0x2, 0x100010d08?})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:911 +0x45
golang.org/x/tools/go/ssa.(*builder).stmt(0xc018d47520?, 0xc018d47520, {0x10081fd60?, 0xc007ed34a0?})
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2218 +0x8d9
golang.org/x/tools/go/ssa.(*builder).buildFunctionBody(0x100238071?, 0xc018d47520)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2327 +0x405
golang.org/x/tools/go/ssa.(*builder).buildFunction(0x1002380c0?, 0xc018d47520)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2267 +0x2e
golang.org/x/tools/go/ssa.(*builder).buildCreated(0xc02d7ffe18)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2349 +0x25
golang.org/x/tools/go/ssa.(*Package).build(0xc019171800)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2529 +0xc66
sync.(*Once).doSlow(0xc007e840d0?, 0xc0072a5788?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
golang.org/x/tools/go/ssa.(*Package).Build(...)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2413
golang.org/x/tools/go/ssa.(*Program).Build.func1(0x0?)
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2398 +0x4c
created by golang.org/x/tools/go/ssa.(*Program).Build
        golang.org/x/tools@v0.1.12/go/ssa/builder.go:2397 +0x19c
```

**Comment by congjunhua** [comment]
```bash
$ go version

go version go1.20.1 darwin/amd64
```

**Comment by ikopyl** [comment]
Consider using [gvm](https://github.com/moovweb/gvm) and installing one of the previous go versions. For example:

```
❯ gvm install go1.18.10
❯ gvm use go1.18.10
❯ gvm list

gvm gos (installed)

=> go1.18.10
   system
```
– after I did these steps, go-callvis started working for me again.

**Comment by congjunhua** [comment]
> 

也可以的，或者自己手动更新下go mod也可以。

**Comment by congjunhua** [comment]
> Consider using [gvm](https://github.com/moovweb/gvm) and installing one of the previous go versions. For example:
> 
> ```
> ❯ gvm install go1.18.10
> ❯ gvm use go1.18.10
> ❯ gvm list
> 
> gvm gos (installed)
> 
> => go1.18.10
>    system
> ```
> 
> – after I did these steps, go-callvis started working for me again.

降低版本肯定是可以的，这个报错就是版本更新导致的，要么降低版本，要么手动更新下 `go mod`，都OK。

**Comment by lctech-daniel-hung** [comment]
Waiting for a fix, I have the same problem

**Comment by congjunhua** [comment]
> Waiting for a fix, I have the same problem

https://github.com/congjunhua/go-callvis

**Comment by lctech-daniel-hung** [comment]
> 

What's the meaning?  pull repo ? , i have tried make install by local but it not woring

**Comment by lctech-daniel-hung** [comment]
我也是1.20不能安裝 , 有拉下來install過了 還是一樣

**Comment by ondrajz** [comment]
This is most likely fixed in the latest version. If not please report again in a new issue. Thank you.
