### ISSUE TITLE
Got error running go-callvis on github.com/googlecloudplatform/gcsfuse

### ISSUE THREAD

**Issue by gargnitingoogle** [ondrajz/go-callvis#170]
```shell
$ go-callvis github.com/googlecloudplatform/gcsfuse
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x602cca]

goroutine 103 [running]:
go/types.(*Checker).handleBailout(0xc00052e000, 0xc000523ba0)
        /usr/lib/google-golang/src/go/types/check.go:339 +0x88
panic({0x8ec2a0?, 0xd4ea50?})
        /usr/lib/google-golang/src/runtime/panic.go:765 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xa44d58?, 0xd51000})
        /usr/lib/google-golang/src/go/types/sizes.go:228 +0x2ea
go/types.(*Config).sizeof(...)
        /usr/lib/google-golang/src/go/types/sizes.go:331
go/types.representableConst.func1({0xa44d58?, 0xd51000?})
        /usr/lib/google-golang/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xa47cf8, 0xd2c7c0}, 0xc00052e000, 0xd51000, 0xc000521d48)
        /usr/lib/google-golang/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xa44d58?, 0xc0001c8180, 0xc00052e000?)
        /usr/lib/google-golang/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc00052e000, 0xc0001c8180, {0xa44d58?, 0xd51000?})
        /usr/lib/google-golang/src/go/types/expr.go:375 +0x2ad
go/types.(*Checker).convertUntyped(0xc00052e000, 0xc0001c8180, {0xa44d58, 0xd51000})
        /usr/lib/google-golang/src/go/types/const.go:289 +0x3f
go/types.(*Checker).matchTypes(0x0?, 0xc0001c8140, 0xc0001c8180)
        /usr/lib/google-golang/src/go/types/expr.go:926 +0x79
go/types.(*Checker).binary(0xc000604ea0?, 0xc0001c8140, {0xa46878?, 0xc0005140f0}, {0xa46908?, 0xc00088e100}, {0xa46e48?, 0xc00088e160}, 0x28, 0x42cd)
        /usr/lib/google-golang/src/go/types/expr.go:800 +0x185
go/types.(*Checker).exprInternal(0xc00052e000, {0x0, 0x0}, 0xc0001c8140, {0xa46878, 0xc0005140f0?}, {0x0?, 0x0?})
        /usr/lib/google-golang/src/go/types/expr.go:1401 +0x1bf4
go/types.(*Checker).rawExpr(0xc00052e000, {0x0, 0x0}, 0xc0001c8140, {0xa46878?, 0xc0005140f0?}, {0x0?, 0x0?}, 0x0)
        /usr/lib/google-golang/src/go/types/expr.go:965 +0x1a5
go/types.(*Checker).expr(0xc00052e000?, {0x0?, 0x0?}, 0x96df56?, {0xa46878?, 0xc0005140f0?})
        /usr/lib/google-golang/src/go/types/expr.go:1498 +0x45
go/types.(*Checker).stmt(0xc00052e000, 0x0, {0xa46c68?, 0xc00080c2c0?})
        /usr/lib/google-golang/src/go/types/stmt.go:573 +0x189d
go/types.(*Checker).stmtList(0xc000683930?, 0x0, {0xc00088e380?, 0x0?, 0x0?})
        /usr/lib/google-golang/src/go/types/stmt.go:124 +0x85
go/types.(*Checker).funcBody(0xc00052e000, 0xc0005124e0, {0xc000500078?, 0x3?}, 0xc00080dd40, 0xc000514180, {0x0, 0x0})
        /usr/lib/google-golang/src/go/types/stmt.go:44 +0x345
go/types.(*Checker).funcDecl.func1()
        /usr/lib/google-golang/src/go/types/decl.go:826 +0x3a
go/types.(*Checker).processDelayed(0xc00052e000, 0x0)
        /usr/lib/google-golang/src/go/types/check.go:446 +0x15c
go/types.(*Checker).checkFiles(0xc00052e000, {0xc000138000, 0x1, 0x1})
        /usr/lib/google-golang/src/go/types/check.go:390 +0x245
go/types.(*Checker).Files(...)
        /usr/lib/google-golang/src/go/types/check.go:344
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001aa000, 0xc0003fee70)
        /usr/local/google/home/gargnitin/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:1052 +0xbdb
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /usr/local/google/home/gargnitin/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:851 +0x1a9
sync.(*Once).doSlow(0x656661736e75?, 0x656661736e75?)
        /usr/lib/google-golang/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /usr/lib/google-golang/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x6675626f69667562?, 0x73657479626f69?)
        /usr/local/google/home/gargnitin/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:839 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x74656e74656e?)
        /usr/local/google/home/gargnitin/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:846 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 96
        /usr/local/google/home/gargnitin/go/pkg/mod/golang.org/x/tools@v0.8.0/go/packages/packages.go:845 +0x94
```

**Comment by ixugo** [comment]
I encountered the same problem。

**Comment by 2048Nemo** [comment]
it's not  supported any my code info at all

**Comment by ning2020** [comment]
+1

**Comment by roman-mc** [comment]
+1

**Comment by roman-mc** [comment]
+1 
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/2051ada0-5f57-4096-966d-514faf2528bd">

**Comment by wangzhankun** [comment]
+1

**Comment by senjixu** [comment]
any help?

**Comment by itroot** [comment]
That worked for me
- https://github.com/ondrajz/go-callvis/pull/177#issuecomment-2237920621
