### ISSUE TITLE
Error import external packages

### ISSUE THREAD

**Issue by Cwilliam** [ondrajz/go-callvis#193]
I'm getting this error when I import this AWS Lamnda package:

```
import "github.com/aws/aws-lambda-go/events"

func main() {
	request := events.APIGatewayProxyRequest{}
	request.Path = "/test"
}
```

The error:
```
$ go-callvis ./... | dot -Tpng -o docs/uml/callvis.png

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6217ef]

goroutine 743 [running]:
go/types.(*Checker).handleBailout(0xc00031f6c0, 0xc000907bf0)
        /usr/local/go/src/go/types/check.go:404 +0x88
panic({0xad1ca0?, 0x1007dc0?})
        /usr/local/go/src/runtime/panic.go:785 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xc567e0, 0x100ecc0})
        /usr/local/go/src/go/types/sizes.go:229 +0x30f
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:334
go/types.representableConst.func1({0xc567e0?, 0x100ecc0?})
        /usr/local/go/src/go/types/const.go:77 +0x86
go/types.representableConst({0xc5a1d8, 0x105f040}, 0xc00031f6c0, 0x100ecc0, 0xc000905658)
        /usr/local/go/src/go/types/const.go:93 +0x173
go/types.(*Checker).representation(0xc00031f6c0, 0xc00050b640, 0x100ecc0)
        /usr/local/go/src/go/types/const.go:257 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc00031f6c0, 0xc00050b640, {0xc567e0, 0x100ecc0})
        /usr/local/go/src/go/types/expr.go:377 +0x2d7
go/types.(*Checker).convertUntyped(0xc00031f6c0, 0xc00050b640, {0xc567e0, 0x100ecc0})
        /usr/local/go/src/go/types/const.go:290 +0x3f
go/types.(*Checker).matchTypes(0xc00031f6c0, 0xc00050b540, 0xc00050b640)
        /usr/local/go/src/go/types/expr.go:928 +0x79
```

**Comment by ondrajz** [comment]
This issue is most likely fixed in #202. Please test if it fixes your issues. Thank you.
