### ISSUE TITLE
"panic: Cannot range over" from go-callvis with golang 1.23.3

### ISSUE THREAD

**Issue by edgan** [ondrajz/go-callvis#201]
After applying PR #177 to fix issue #197 I ran into these errors when using golang `1.23.3`. Downgrading to golang `1.19.13` solves both this issue, and issue #197.

Error from project one:
```
panic: Cannot range over: func(yield func(*golang.org/x/net/html.Node) bool)

goroutine 2267 [running]:
golang.org/x/tools/go/ssa.(*builder).rangeStmt(0xc00e94f3f0, 0xc00c761040, 0xc00995b320, 0x0)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2279 +0x805
golang.org/x/tools/go/ssa.(*builder).stmt(0xc00e94f3f0, 0xc00c761040, {0xc18a80?, 0xc00995b320?})
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2503 +0x205
golang.org/x/tools/go/ssa.(*builder).stmtList(...)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:909
golang.org/x/tools/go/ssa.(*builder).stmt(0xc00e94f3f0, 0xc00c761040, {0xc18900?, 0xc00d422d80?})
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2465 +0xe47
golang.org/x/tools/go/ssa.(*builder).buildFromSyntax(0xc00e94f3f0, 0xc00c761040)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2577 +0x245
golang.org/x/tools/go/ssa.(*builder).buildFunction(0xac1cc0?, 0xc00c761040)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2531 +0x17b
golang.org/x/tools/go/ssa.(*builder).iterate(0xc00e94f3f0)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2519 +0x25
golang.org/x/tools/go/ssa.(*Package).build(0xc00f04e980)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2648 +0xa9
sync.(*Once).doSlow(0xc0002de7b8?, 0x6d4d78?)
	/usr/lib/golang/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/usr/lib/golang/src/sync/once.go:67
golang.org/x/tools/go/ssa.(*Package).Build(...)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2637
golang.org/x/tools/go/ssa.(*Program).Build.func1(0x69746e7572220909?)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2620 +0x45
created by golang.org/x/tools/go/ssa.(*Program).Build in goroutine 1
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2619 +0x187
```

Error from project two:
```
panic: Cannot range over: func(yield func(E) bool)

goroutine 2027 [running]:
golang.org/x/tools/go/ssa.(*builder).rangeStmt(0xc013097780, 0xc0116dc680, 0xc0035263c0, 0x0)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2279 +0x805
golang.org/x/tools/go/ssa.(*builder).stmt(0xc013097780, 0xc0116dc680, {0xc18a80?, 0xc0035263c0?})
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2503 +0x205
golang.org/x/tools/go/ssa.(*builder).stmtList(...)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:909
golang.org/x/tools/go/ssa.(*builder).stmt(0xc013097780, 0xc0116dc680, {0xc18900?, 0xc00328ccc0?})
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2465 +0xe47
golang.org/x/tools/go/ssa.(*builder).buildFromSyntax(0xc013097780, 0xc0116dc680)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2577 +0x245
golang.org/x/tools/go/ssa.(*builder).buildFunction(0xac1cc0?, 0xc0116dc680)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2531 +0x17b
golang.org/x/tools/go/ssa.(*builder).iterate(0xc013097780)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2519 +0x25
golang.org/x/tools/go/ssa.(*Package).build(0xc01147af80)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2648 +0xa9
sync.(*Once).doSlow(0xc0007a0fb8?, 0x6d4d78?)
	/usr/lib/golang/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/usr/lib/golang/src/sync/once.go:67
golang.org/x/tools/go/ssa.(*Package).Build(...)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2637
golang.org/x/tools/go/ssa.(*Program).Build.func1(0x0?)
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2620 +0x45
created by golang.org/x/tools/go/ssa.(*Program).Build in goroutine 1
	/home/ngrennan/go/pkg/mod/golang.org/x/tools@v0.19.0/go/ssa/builder.go:2619 +0x187
```

**Comment by ondrajz** [comment]
I have opened new PR #202 that should fix this issue. Please, try it out to confirm the issue above is fixed.
